### ISSUE TITLE
Fetching historical data

### ISSUE THREAD

**Issue by dmspils** [mhvis/solar#23]
The docs still say "To Do" for fetching historical data. Any pointers for getting the daily totals for a given date would be really helpful.

**Comment by mhvis** [comment]
Yes indeed. It was not implemented because I had no need for it. It would work the same way as fetching historic data with the SolarPower Browser V3 app. See http://mhvis.github.io/solar/ for a link to that app. You could try to download and run that app. The app should allow you to download historical data.

If you know Python and low level networking you can create a script yourself based on the info on the previous link.
